=== visualkhh/doc-visualkhh/컴퓨터/xml/소설같은xml/novelxml_src/09_XML_Schema/UserDefinedDataType/booklist.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  <xsd:element name="booklist">
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element name="book" minOccurs="1" maxOccurs="unbounded">
          <xsd:complexType>
            <xsd:sequence>
              <xsd:element name="part">
                <xsd:simpleType>
                  <xsd:restriction base="xsd:string">
                    <xsd:enumeration value="XML" />
                    <xsd:enumeration value="XSLT" />
                    <xsd:enumeration value="Schema" />
                  </xsd:restriction>
                </xsd:simpleType>
              </xsd:element>
              <xsd:element name="name" type="xsd:string" />
              <xsd:element name="page">
                <xsd:simpleType>
                  <xsd:restriction base="xsd:integer">
                    <xsd:minInclusive value="1" />
                    <xsd:maxInclusive value="1500" />
                  </xsd:restriction>
                </xsd:simpleType>
              </xsd:element>
            </xsd:sequence>
          </xsd:complexType>
        </xsd:element>
      </xsd:sequence>
    </xsd:complexType>
  </xsd:element>
</xsd:schema>

=== visualkhh/doc-visualkhh/컴퓨터/xml/소설같은xml/novelxml_src/09_XML_Schema/UserDefinedDataType/booklist.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>

<booklist xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xsi:noNamespaceSchemaLocation="booklist.xsd">
	<book>
		<part>XML</part>
		<name>Professional VB6 XML</name>
		<page>648</page>
	</book>
	<book>
		<part>XSLT</part>
		<name>XSLT Programmer's Reference</name>
		<page>464</page>
	</book>
</booklist>
