=== visualkhh/doc-visualkhh/컴퓨터/xml/소설같은xml/novelxml_src/05_SAX_Programming/UseErrorHandler/SAXSample.dtd
<!ELEMENT	booklist	(book+)>
<!ELEMENT	book		(name, authors, page, publish?, price)>
<!ELEMENT	name		(#PCDATA)>
<!ELEMENT	authors		(author+)>
<!ELEMENT	author		(#PCDATA)>
<!ELEMENT	page		(#PCDATA)>
<!ELEMENT	publish		EMPTY>
<!ELEMENT	price		(#PCDATA)>
	
<!ATTLIST	book		isbn	ID	#REQUIRED>
<!ATTLIST	name		outpage	CDATA	#IMPLIED>
<!ATTLIST	publish		year	CDATA	#IMPLIED
				month	CDATA	#IMPLIED
				day	CDATA	#IMPLIED>
<!ATTLIST	price		unit	CDATA	"won">

=== visualkhh/doc-visualkhh/컴퓨터/xml/소설같은xml/novelxml_src/05_SAX_Programming/ExtDeclHandler/SAXSample.xml
<?xml version="1.0" encoding="euc-kr" standalone="no"?>

<!DOCTYPE booklist SYSTEM "SAXSample.dtd">

<!-- 책 정보에 관한 XML -->

<booklist>
	<book isbn="h0-596-00762-0">
		<name outpage="ProgrammingNETComponents.gif">
			&bookname;
		</name>
		<authors>
			<author>Juval Lowy</author>
		</authors>
		<page><![CDATA[ 648 ]]></page>
		<publish year="2005" month="06" />
		<price unit="won">51300</price>
	</book>
</booklist>
