<?xml version="1.0" encoding="euc-kr"?>
 
<!DOCTYPE BookList [
<!ELEMENT BookList (Book+)>
<!ELEMENT Book (Title, Author*, Price, (PubDate | Date)?)>
<!ATTLIST Book ISBN ID #REQUIRED>
<!ELEMENT Title (#PCDATA)>
<!ELEMENT Author (#PCDATA)>
<!ELEMENT Price (#PCDATA)>
<!ATTLIST Price unit (원 | 달러 | 엔) #REQUIRED>
<!ELEMENT PubDate EMPTY>
<!ATTLIST PubDate year CDATA #REQUIRED
                  month CDATA #REQUIRED>
<!ELEMENT Date EMPTY>
]>
 
<BookList>
	<Book ISBN="X134-9821235">
		<Title>XML 프로그래밍</Title>
		<Author>아무게</Author>
		<Price unit="달러">23.4</Price>
		<PubDate year="2004" month="05"/>
	</Book>
	<Book ISBN="X134-9821235">
		<Title>XML 프로그래밍</Title>
		<Price unit="유로">23.4</Price>
	</Book>
</BookList>