=== visualkhh/doc-visualkhh/컴퓨터/xml/소설같은xml/novelxml_src/09_XML_Schema/ComplexFromSimple/booklist.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  <xsd:element name="booklist">
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element name="book" minOccurs="1" maxOccurs="unbounded">
          <xsd:complexType>
            <xsd:sequence>
              <xsd:element name="name">
                <xsd:complexType>
                  <xsd:simpleContent>
                    <xsd:extension base="xsd:string">
                      <xsd:attribute name="part" use="optional">
                        <xsd:simpleType>
                          <xsd:restriction base="xsd:string">
                            <xsd:enumeration value="XML" />
                            <xsd:enumeration value="XSLT" />
                            <xsd:enumeration value="Schema" />
                          </xsd:restriction>
                        </xsd:simpleType>
                      </xsd:attribute>
                    </xsd:extension>
                  </xsd:simpleContent>
                </xsd:complexType>
              </xsd:element>
              <xsd:element name="authors">
                <xsd:complexType>
                  <xsd:sequence>
                    <xsd:element name="author" type="xsd:string" minOccurs="0" maxOccurs="unbounded"/>
                  </xsd:sequence>
                </xsd:complexType>
              </xsd:element>
              <xsd:element name="page">
                <xsd:simpleType>
                  <xsd:restriction base="xsd:integer">
                    <xsd:minInclusive value="1" />
                    <xsd:maxInclusive value="1500" />
                  </xsd:restriction>
                </xsd:simpleType>
              </xsd:element>
              <xsd:element name="publish" minOccurs="0" maxOccurs="1">
                <xsd:complexType>
                  <xsd:attribute name="year" type="xsd:integer" use="optional" />
                  <xsd:attribute name="month" use="optional">
                    <xsd:simpleType>
                      <xsd:restriction base="xsd:integer">
                        <xsd:minInclusive value="1" />
                        <xsd:maxInclusive value="12" />
                      </xsd:restriction>
                    </xsd:simpleType>
                  </xsd:attribute>
                  <xsd:attribute name="date" use="optional">
                    <xsd:simpleType>
                      <xsd:restriction base="xsd:integer">
                        <xsd:minInclusive value="1" />
                        <xsd:maxInclusive value="30" />
                      </xsd:restriction>
                    </xsd:simpleType>
                  </xsd:attribute>
                </xsd:complexType>
              </xsd:element>
              <xsd:element name="price">
                <xsd:complexType>
                  <xsd:simpleContent>
                    <xsd:extension base="xsd:integer">
                      <xsd:attribute name="unit" use="optional" default="won">
                        <xsd:simpleType>
                          <xsd:restriction base="xsd:string">
                            <xsd:enumeration value="won" />
                            <xsd:enumeration value="dollor" />
                          </xsd:restriction>
                        </xsd:simpleType>
                      </xsd:attribute>
                    </xsd:extension>
                  </xsd:simpleContent>
                </xsd:complexType>
              </xsd:element>
            </xsd:sequence>
            <xsd:attribute name="isbn" type="xsd:ID" use="required" />
          </xsd:complexType>
        </xsd:element>
      </xsd:sequence>
    </xsd:complexType>
  </xsd:element>
</xsd:schema>

=== visualkhh/doc-visualkhh/컴퓨터/xml/소설같은xml/novelxml_src/09_XML_Schema/ComplexFromSimple/booklist.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>

<booklist xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xsi:noNamespaceSchemaLocation="booklist.xsd">
	<book isbn="h0-596-00762-0">
		<name part="XML">Professional VB6 XML</name>
		<authors>
			<author>Juval Lowy</author>
		</authors>
		<page>648</page>
		<publish year="2005" month="06" />
		<price unit="won">51300</price>
	</book>
	<book isbn="h0-596-10068-X">
		<name part="XSLT">XSLT Programmer's Reference</name>
		<authors>
			<author>eBay Hacks, Second Edition</author>
		</authors>
		<page>464</page>
		<publish year="2005" month="06" />
		<price unit="won">28500</price>
	</book>
</booklist>
